# Generated by Django 5.2.7 on 2026-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_remove_documentogenerado_archivos_archivogenerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecategoria',
            name='tipo_dato',
            field=models.CharField(choices=[('text', 'Texto'), ('date', 'Fecha'), ('number', 'Número'), ('percent', 'Porcentaje'), ('auto', 'Automático')], default='text', max_length=20),
        ),
    ]
