# Generated by Django 6.0.3 on 2026-03-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_alter_variablecategoria_tipo_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='cloudinary_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(blank=True, upload_to='plantillas/'),
        ),
    ]
